services:
  reverse-proxy:
    image: ghcr.io/jeromba6/fs-2025-01-docker/reverse-proxy:${VERSION}
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - static-webserver
      - api-server1
      - api-server2
    build:
      context: reverse-proxy
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/health", "-k"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  static-webserver:
    image: ghcr.io/jeromba6/fs-2025-01-docker/static-webserver:${VERSION}
    container_name: static-webserver
    build:
      context: static-webserver
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  api-server1:
    image: ghcr.io/jeromba6/fs-2025-01-docker/api-server:${VERSION}
    container_name: api-server1
    build:
      context: api-server
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    environment:
      PORT: 5001

  api-server2:
    image: ghcr.io/jeromba6/fs-2025-01-docker/api-server:${VERSION}
    container_name: api-server2
    # No build context specified, using the same image as api-server1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    environment:
      PORT: 5002
