
services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    user: root:root
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yml
      - /tmp/loki:/tmp/loki
      - loki-data:/loki
      - loki-wal:/wal
    command: -config.file=/etc/loki/local-config.yml
    # entrypoint: sleep 100000

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id
      - /etc/hostname:/etc/hostname
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

networks:
  logging:
    driver: bridge

volumes:
  loki-data:
  loki-wal:
  grafana-data: