name: Publish Docker image
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write
  issues: write
  statuses: write
  checks: write
  deployments: write
  repository-projects: write

jobs:
  set_env:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.setenv.outputs.repo }}
      release: ${{ steps.setenv.outputs.release }}
    steps:
      - name: Set environment variables
        id: setenv
        run: |
          echo "repo=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
          echo "release=${GITHUB_SHA}" >> $GITHUB_OUTPUT

  # --- Separate Linting Jobs (run before builds) ---

  lint_python:
    runs-on: ubuntu-latest
    needs: set_env # Depends on set_env for general workflow flow
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Use '3.x' for latest or specify a version like '3.9'
      - name: Install Pylint
        run: pip install pylint
      - name: Run Pylint on api-server
        run: pylint api-server

  lint_yaml:
    runs-on: ubuntu-latest
    needs: set_env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Yamllint
        run: pip install yamllint
      - name: Run Yamllint
        run: python3 -m yamllint -d relaxed $(find . -name "*.yml" -o -name "*.yaml")

  lint_dockerfile_api:
    runs-on: ubuntu-latest
    needs: set_env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hadolint for api-server Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: api-server/Dockerfile

  lint_dockerfile_proxy:
    runs-on: ubuntu-latest
    needs: set_env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hadolint for reverse-proxy Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: reverse-proxy/Dockerfile

  lint_dockerfile_static:
    runs-on: ubuntu-latest
    needs: set_env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hadolint for static-webserver Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: static-webserver/Dockerfile

  lint_docker_compose:
    runs-on: ubuntu-latest
    needs: set_env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Docker Compose Lint
        uses: sjafferali/docker-compose-lint-action@v0.1.2
        with:
          compose-file: './compose.yml'

  # --- Build Jobs (now depend on relevant linting jobs) ---

  build_api:
    runs-on: ubuntu-latest
    needs: [set_env, lint_python, lint_yaml, lint_dockerfile_api, lint_docker_compose] # Added linting job dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: api-server
          file: api-server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ needs.set_env.outputs.repo }}/api-server:${{ needs.set_env.outputs.release }}

  build_static:
    runs-on: ubuntu-latest
    needs: [set_env, lint_yaml, lint_dockerfile_static, lint_docker_compose] # Added linting job dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: static-webserver
          file: static-webserver/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ needs.set_env.outputs.repo }}/static-webserver:${{ needs.set_env.outputs.release }}

  build_proxy:
    runs-on: ubuntu-latest
    needs: [set_env, lint_yaml, lint_dockerfile_proxy, lint_docker_compose] # Added linting job dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: reverse-proxy
          file: reverse-proxy/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ needs.set_env.outputs.repo }}/reverse-proxy:${{ needs.set_env.outputs.release }}

  # --- Integration Test Job (now only depends on successful builds) ---

  integration_test:
    runs-on: ubuntu-latest
    needs: [build_api, build_static, build_proxy] # Only needs the build jobs, as linting is covered upstream
    steps:
      - uses: actions/checkout@v3
      - run: |
          export VERSION=${{ github.sha }}
          docker compose -f compose.yml up -d
      - run: |
          echo "Waiting for containers to be healthy..."
          for service in reverse-proxy static-webserver api-server1 api-server2; do
            for i in {1..10}; do
              if docker inspect --format='{{json .State.Health.Status}}' $service | grep -q '"healthy"'; then
                echo "$service is healthy"
                break
              fi
              sleep 5
            done
          done
      - run: |
          echo "Running tests..."
          curl -f https://localhost/health -k || exit 1
          curl -f https://localhost/api/health -k || exit 1
          curl -f https://localhost -k || exit 1
