name: Publish Docker image
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write
  issues: write
  statuses: write
  checks: write
  deployments: write
  repository-projects: write
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set releaase
        run: |
          echo "REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api-server Docker image
        uses: docker/build-push-action@v2
        with:
          context: api-server
          file: api-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.REPO }}/api-server:test

      - name: Build and push static-webserver Docker image
        uses: docker/build-push-action@v2
        with:
          context: static-webserver
          file: static-webserver/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.REPO }}/static-webserver:test

      - name: Build and push reverse-proxy Docker image
        uses: docker/build-push-action@v2
        with:
          context: reverse-proxy
          file: reverse-proxy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.REPO }}/reverse-proxy:test

